name: MasterDeployCI
on:
  push:
    branches:
      - master
runs:
  using: 'node16'
  main: 'index.js'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "bensondavis61@gmail.com"
        git config --global user.name "bensondavis"
        git remote set-url origin https://${{secrets.GH_PAGE_SECRETS}}@github.com/bensondavis/hangman.git
        npm run deploy