name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install --legacy-peer-deps
    - name: Deploy to GH Pages
      run: |
        git config --global user.email "bensondavis61@gmail.com"
        git config --global user.name "bensondavis"
        git remote set-url origin https://${{secrets.GH_PAGE_SECRETS}}@github.com/bensondavis/hangman.git
        npm run deploy